name: clock_analog
description: Clock Analog is used to pick time of day (without dialog box).
  User can use this package to add widgets of analog clock picker on screen,
  and can retrieve selected time with onChange event.

version: 0.0.3
homepage: https://github.com/rikun5989/clock_analog

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
