name: clock_analog
description: Clock Analog is used to pick time of day (without dialog box).
  User can use this package to add widgets of analog clock picker on screen,
  and can retrieve selected time with onChange event. This package has hour
  and minute time selection with AM and PM selection. Based on AM and PM selection,
  onChange event will return selected time in tweenty four hours format. Selection of
  time is availbale in 12 hours format only and with AM - PM selection. User need to
  provide initial time as it is required parameter.

version: 0.0.2
homepage: https://github.com/rikun5989/clock_analog

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
